### PR TITLE
Add section problems notebook

### PR DESCRIPTION
**Pull request by KristianVangsnes**

### CODE REVIEW

**Comment by StigHaraldGustavsen** [comment]
Struggling with the .env and python-dotenv on this branch, it works on the other branch. and it does install with poetry install, but I does not load the module. and the library is in the .venv/lib aswell, so it should find it.

image

**Comment by StigHaraldGustavsen** [comment]
does work with in a ordinary python interpreter 
image

**Comment by KristianVangsnes** [comment]
It works for me. Have you used the correct kernel in vs-code? It should find dotenv.

**Review by StigHaraldGustavsen — APPROVED** [review]
I got the .env to work on another machine.  but This PR is not on the update main, with regards to that some of the files still contain referances to cognite-sdk-core, but I don't know if that matters.

**Pull request merged**
